### ISSUE TITLE
Typo: Word "TDVM_ID" should be "TPM_ID"

### ISSUE THREAD

**Issue by liuw1** [intel/vtpm-td#103]
https://github.com/intel/vtpm-td/blob/abf493e91e307377612ddee0fb0d175976d6a2fa/src/protocol/src/wait_for_request/command.rs#L22

https://github.com/intel/vtpm-td/blob/abf493e91e307377612ddee0fb0d175976d6a2fa/src/protocol/src/wait_for_request/response.rs#L24

**Comment by mxu9** [comment]
Refer to vtpm spec Table 14

**Comment by liuw1** [comment]
Also need to update function name:
set_tdvm_id
get_tdvm_id
