### ISSUE TITLE
EK cert cannot pass openssl verification

### ISSUE THREAD

**Issue by liuw1** [intel/vtpm-td#116]
The ek-cert failed to pass the openssl verify command.

steps:
1. export ca-cert from tpm2 nv to ca_cert.bin
2. export ek-cert from tpm2 nv to ek_cert.bin
3. convert der to pem format
    openssl x509 -inform DER -in ca_cert.bin -outform PEM -out ca_cert.pem
    openssl x509 -inform DER -in ek_cert.bin -outform PEM -out ek_cert.pem
4. call openssl command to verify the self-signed ca-cert
    openssl verify -CAfile ca_cert.pem ek_cert.pem

**Comment by mxu9** [comment]
This issue is caused by the wrong extension format in ek-certificate.
