### ISSUE TITLE
Issue found during reset user td cycle test

### ISSUE THREAD

**Issue by liuw1** [intel/vtpm-td#47]
ERROR - verify finish request signature errorERROR - Received unknown SPDM command
INFO - Reset spdm-session
INFO - shutdown the tpm
INFO - receive_message!
INFO - Data received 28 bytes.
INFO - send spdm version
INFO - Send data 60 bytes.
ERROR - Unexpected state! SpdmSessionHandshaking : SpdmSessionNotStartedINFO - Reset spdm-session
INFO - receive_message!
INFO - Data received 44 bytes.
INFO - Send data 52 bytes.
ERROR - Unexpected state! SpdmSessionHandshaking : SpdmSessionNotStartedINFO - Reset spdm-session
INFO - receive_message!
INFO - Data received 28 bytes.
INFO - send spdm version
INFO - Send data 60 bytes.

**Comment by liuw1** [comment]
a6700f936bd02a907d92b5c0d4dfb620d79fde0e

**Comment by liuw1** [comment]
Reopen this issue.

**Comment by liuw1** [comment]
This random issue reproduced 3 times in CI actions.

**Comment by sunceping** [comment]
We tried the test shown below and there is no reproduction to this issue：
(rust-spdm :[4b10086)](https://github.com/intel/rust-spdm/tree/4b100862a050a79e9cdacbfbc7ef16b0b0662aca)
(libspdm: [55f5141](https://github.com/DMTF/libspdm/tree/55f5141436d2f6debf4b7cd57641cc78d8e4c6fc))
Use rust-spdm-emu as responder:
  Test with  rust-spdm-emu-requester 3000 cycle without reproducing
  Test with spdm-emu (libspdm)-requester, 3000 cycles, also not reproduced.

**Comment by sunceping** [comment]
The root cause of this problem is that TDVF makes an error when saving the private key，
Fix the issue in TDVF [451](https://github.com/tianocore/edk2-staging/pull/451) , 
Test with vtpm  2000 cycle  without  this problem
 Check the log of TDVF, the pubkey size is chaged to 95 bytes 14  times, and the private key size is changed to 47 bytes 5 times
