### ISSUE TITLE
need calculate the theoretical value for memory usage 

### ISSUE THREAD

**Issue by jyao1** [intel/vtpm-td#54]
total = common + per_spdm_connection * MAX_SPDM_CONNECTION + per_tpm_instance * MAX_TPM_INSTANCE

**Comment by jyao1** [comment]
Currently, MAX_SPDM_CONNECTION and MAX_TPM_INSTANCE is 1.

**Comment by jyao1** [comment]
We probably need run all vTPM command to calculate the peak value.

**Comment by mxu9** [comment]
> We probably need run all vTPM command to calculate the peak value.

A new issue is created for this comment. #110

**Comment by mxu9** [comment]
In #115  the tpm2 commands coverage is 91/99 (~91.9%).
