### ISSUE TITLE
TDVF does not support RTMR based attestation if the environment support VTPM

### ISSUE THREAD

**Issue by liuw1** [intel/vtpm-td#62]
```
  // If VMCALL_SERVICE_VTPM_GUID is not supported, VMM will not

  // allow tdvf to send and receive VTPM messages over an spdm session.

  Status = TdQueryServiceForVtpm ();

  if (!EFI_ERROR (Status)) {

    VTpmEnabled = TRUE;

    BuildGuidHob(&gEdkiiVTpmBasedMeasurementHobGuid, 0);

  }
```

**Comment by jyao1** [comment]
@liuw1 Please describe clearly what the problem is.

**Comment by liuw1** [comment]
@jyao1 Current status is that when we launch TDVF on vTPM supported environment (pass service query) without vTPM td running, we cannot find CCEL ACPI table in guest OS. 
Is that a correct haviour?

**Comment by jyao1** [comment]
If VMM reports vTPM supported, then we switch to vTPM path. No RTMR and CCEL. That is right behavior.
If VMM stops vTPM, then it is a DOS attack.

**Comment by liuw1** [comment]
Thanks for the clarification. This is not an issue, close it.
